default:
  image: mcr.microsoft.com/dotnet/sdk:6.0

build-debug:
    stage: build
    before_script:
        - apt-get update -y
        - apt-get install zip -y
        - apt-get install libfreetype6 -y
    script:
    - dotnet build -c Debug

build-release:
    stage: build
    before_script:
        - apt-get update -y
        - apt-get install zip -y
        - apt-get install libfreetype6 -y
    script:
    - dotnet build -c Release 

unit-test:
    stage: test
    script:
        - 'dotnet test --test-adapter-path:. --logger:"junit;LogFilePath=..\artifacts\{assembly}-test-result.xml;MethodFormat=Class;FailureBodyFormat=Verbose"'
    artifacts:
        when: always
        expire_in: 1 weeks
        paths:
            - ./**/*test-result.xml
        reports:
            junit:
                - ./**/*test-result.xml

deploy:
    stage: deploy
    script:
        - apt-get update -y
        - apt-get install zip -y
        - apt-get install libfreetype6 -y
        - dotnet publish -c Release -r win-x64 -o ./MazeGame /p:PublishReadyToRun=false /p:TieredCompilation=false --self-contained --configuration release
        - zip -r MazeGame.zip ./MazeGame
    artifacts:
        when: always
        expire_in: 2 weeks
        paths:
            - ./MazeGame.zip
