default:
  image: mcr.microsoft.com/dotnet/sdk:6.0

build-debug:
    stage: build
    script:
    - dotnet build -c Debug

build-release:
    stage: build
    script:
    - dotnet build -c Release 

unit-test:
    stage: test
    script:
        - 'dotnet test --test-adapter-path:. --logger:"junit;LogFilePath=..\artifacts\{assembly}-test-result.xml;MethodFormat=Class;FailureBodyFormat=Verbose"'
    artifacts:
        when: always
        expire_in: 1 weeks
        paths:
            - ./**/*test-result.xml
        reports:
            junit:
                - ./**/*test-result.xml

deploy:
    stage: publish
    script:
        - dotnet publish -c Release -o ./MazeGame
        - zip -r MazeGame.zip ./MazeGame
    artifacts:
        when: always
        expire_in: 2 weeks
            - ./MazeGame.zip

